### ISSUE TITLE
Getting exceptions While Using "multiprocTCPBase" and logdefs in virtualenvironment 

### ISSUE THREAD

**Issue by dencilphani** [thespianpy/Thespian#57]
Process Actor___main__.Rossup__ActorAddr-LocalAddr.0:
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\1187598\PycharmProjects\pythonProject1\venv\lib\site-packages\thespian\system\multiprocCommon.py", line 561, in startChild
    for key in logDefs ])))
  File "C:\Users\1187598\PycharmProjects\pythonProject1\venv\lib\site-packages\thespian\system\multiprocCommon.py", line 549, in <lambda>
    minLevelIn = lambda l: min(list(l)) if list(l) else 0
ValueError: min() arg is an empty sequence

**Comment by kquick** [comment]
Can you provide a copy of what you are passing as the `logDefs` parameter of your `ActorSystem(...)` call?  Please feel free to sanitize names and paths, but I'm interested in how this is getting past the list validation check.

**Comment by dencilphani** [comment]
Hi Kevin , Thank you for the quick reply 
Code is working fine in one environment and is facing error while using in venv ,Later it started working after placing sleep of 2 sec after Actor Creation but Log defs is throwing error 

**Actor system call**
```
act = ActorSystem("multiprocTCPBase", logDefs=logcfg)
Parent_Actor = act.createActor(parent)
act.tell(Parent_Actor , new_id)

```
this is the **logcfg** am using 
``
class actorLogFilter(logging.Filter):
    def filter(self, logrecord):
        return 'actorAddress' in logrecord.__dict__


class notActorLogFilter(logging.Filter):
    def filter(self, logrecord):
        return 'actorAddress' not in logrecord.__dict__


logcfg = {'version': 1,
          'formatters': {
              'normal': {'format': '%(asctime)s \t [%(levelname)s | %(filename)s:%(name)s] => %(message)s'},
              'actor': {'format': '%(asctime)s \t [%(levelname)s | %(filename)s:%(name)s] %(actorAddress)s => %(message)s'}},
          'filters': {'isActorLog': {'()': actorLogFilter},
                      'notActorLog': {'()': notActorLogFilter}},
          'handlers': {'h1': {'class': 'logging.FileHandler',
                              'filename': req_dirname+'/'+'{:%Y-%m-%d}.log'.format(datetime.now()),
                              'formatter': 'normal',
                              'filters': ['notActorLog'],
                              'level': logging.INFO},
                       'h2': {'class': 'logging.FileHandler',
                              'filename': req_dirname+'/'+'{:%Y-%m-%d}.log'.format(datetime.now()),
                              'formatter': 'actor',
                              'filters': ['isActorLog'],
                              'level': logging.INFO}, },
          'loggers': {'': {'handlers': ['h1', 'h2'], 'level': logging.DEBUG}}
          }

@kquick  i would like to know what should be the delay for an actor system should be made and also the wakup delay for the Actor system to monitor a process

**Comment by kquick** [comment]
Thanks for the bug report! I've fixed this in version 3.10.3 which was just released.

It should not be necessary to add any delay for actor creation.  The actor creation is done asynchronously, but the various communications are buffered and will wait for this creation to complete.  If this doesn't answer your question, please feel free to  ask with more details and I'm happy to answer.

**Comment by dencilphani** [comment]
@kquick  Thank you for the update
`Logdefs` working fine in  version 3.10.3  
I think in `venv `the `multiprocTCPBase `is not getting forked in the background , am verifying in windows version 
as i am running the same code outside venv its getting forked and checking the process , but not happening in `venv`
Correct me if am wrong

**Comment by kquick** [comment]
I am doubtful that `venv` could affect the ability to create new processes.  The `venv` should only be controlling the visible python dependences (and the visible executable), but Thespian has no needed dependencies.  It can make use of the setproctitle package if it's available, but it should be optional.  Please let me know what environments you are seeing this in and what you find out.   Thanks!

**Comment by dencilphani** [comment]
@kquick Thank you for the immediate support 
Now its working fine

**Comment by kquick** [comment]
Great news, @dencilphani !
